export const cpu = [
  {
    category: ['default'],
    firm: 'AMD',
    branding: 'Ryzen 3',
    model: '1200',
    series: 1000,
    cores: 4,
    graphics: false,
    socket: 'AM4',
    tdp: 65,
    pcie: 3,
    price: 1,
    solutions: ['GTX 1650'],
  },
  {
    category: ['default', 'gaming'],
    firm: 'AMD',
    branding: 'Ryzen 5',
    model: '1600',
    series: 1000,
    cores: 6,
    graphics: false,
    socket: 'AM4',
    tdp: 65,
    pcie: 3,
    price: 2,
    solutions: [
      'GTX 1650',
      'GTX 1650 super',
      'GTX 1660',
      'GTX 1660 super',
      'RTX 3050',
    ],
  },
  {
    category: ['default', 'gaming'],
    firm: 'AMD',
    branding: 'Ryzen 5',
    model: '1600X',
    series: 1000,
    cores: 6,
    graphics: false,
    socket: 'AM4',
    tdp: 95,
    pcie: 3,
    price: 4,
    solutions: [
      'GTX 1650',
      'GTX 1650 super',
      'GTX 1660',
      'GTX 1660 super',
      'RTX 3050',
    ],
  },
  {
    category: ['default', 'gaming', 'hardwork'],
    firm: 'AMD',
    branding: 'Ryzen 7',
    model: '1700',
    series: 1000,
    cores: 8,
    graphics: false,
    socket: 'AM4',
    tdp: 65,
    pcie: 3,
    price: 4,
    solutions: [
      'GTX 1660 super',
      'GTX 1660 Ti',
      'RTX 3050',
      'RTX 3060',
      'RTX 4060',
    ],
  },
  {
    category: ['default', 'gaming', 'hardwork'],
    firm: 'AMD',
    branding: 'Ryzen 7',
    model: '1700X',
    series: 1000,
    cores: 8,
    graphics: false,
    socket: 'AM4',
    tdp: 95,
    pcie: 3,
    price: 5,
    solutions: [
      'GTX 1660 super',
      'GTX 1660 Ti',
      'RTX 3050',
      'RTX 3060',
      'RTX 4060',
    ],
  },
  {
    category: ['default'],
    firm: 'AMD',
    branding: 'Ryzen 3',
    model: '2200G',
    series: 2000,
    cores: 4,
    graphics: true,
    socket: 'AM4',
    tdp: 65,
    pcie: 1,
    price: 1,
    solutions: ['Vega'],
  },
  {
    category: ['default'],
    firm: 'AMD',
    branding: 'Ryzen 3',
    model: '2300X',
    series: 2000,
    cores: 4,
    graphics: false,
    socket: 'AM4',
    tdp: 65,
    pcie: 3,
    price: 2,
    solutions: ['GTX 1650'],
  },
  {
    category: ['default', 'gaming'],
    firm: 'AMD',
    branding: 'Ryzen 5',
    model: '2600',
    series: 2000,
    cores: 6,
    graphics: false,
    socket: 'AM4',
    tdp: 65,
    pcie: 3,
    price: 3,
    solutions: [
      'GTX 1660 super',
      'GTX 1660 Ti',
      'RTX 3050',
      'RTX 3060',
      'RTX 4060',
    ],
  },
  {
    category: ['default', 'gaming', 'hardwork'],
    firm: 'AMD',
    branding: 'Ryzen 7',
    model: '2700',
    series: 2000,
    cores: 8,
    graphics: false,
    socket: 'AM4',
    tdp: 65,
    pcie: 3,
    price: 4,
    solutions: [
      'GTX 1660 super',
      'GTX 1660 Ti',
      'RTX 3050',
      'RTX 3060',
      'RTX 3060 Ti',
    ],
  },
  {
    category: ['default', 'gaming', 'hardwork'],
    firm: 'AMD',
    branding: 'Ryzen 7',
    model: '2700X',
    series: 2000,
    cores: 8,
    graphics: false,
    socket: 'AM4',
    tdp: 105,
    pcie: 3,
    price: 5,
    solutions: [
      'GTX 1660 super',
      'GTX 1660 Ti',
      'RTX 3050',
      'RTX 3060',
      'RTX 3060 Ti',
      'RTX 4060',
    ],
  },
  {
    category: ['default'],
    firm: 'AMD',
    branding: 'Ryzen 3',
    model: '3200G',
    series: 3000,
    cores: 4,
    graphics: true,
    socket: 'AM4',
    tdp: 65,
    pcie: 3,
    price: 1,
    solutions: ['Vega'],
  },
  {
    category: ['default'],
    firm: 'AMD',
    branding: 'Ryzen 3',
    model: '3100',
    series: 3000,
    cores: 4,
    graphics: false,
    socket: 'AM4',
    tdp: 65,
    pcie: 4,
    price: 2,
    solutions: [
      'GTX 1650',
      'GTX 1650 super',
      'GTX 1660',
      'GTX 1660 super',
      'GTX 1660 Ti',
    ],
  },
  {
    category: ['default', 'gaming'],
    firm: 'AMD',
    branding: 'Ryzen 5',
    model: '3600',
    series: 3000,
    cores: 6,
    graphics: false,
    socket: 'AM4',
    tdp: 65,
    pcie: 4,
    price: 3,
    solutions: ['GTX 1660 super', 'GTX 1660 Ti', 'RTX 3050', 'RTX 3060'],
  },
  {
    category: ['default', 'gaming'],
    firm: 'AMD',
    branding: 'Ryzen 5',
    model: '3600X',
    series: 3000,
    cores: 6,
    graphics: false,
    socket: 'AM4',
    tdp: 95,
    pcie: 4,
    price: 4,
    solutions: [
      'GTX 1660 super',
      'GTX 1660 Ti',
      'RTX 3050',
      'RTX 3060',
      'RTX 4060',
    ],
  },
  {
    category: ['default', 'gaming', 'hardwork'],
    firm: 'AMD',
    branding: 'Ryzen 7',
    model: '3700X',
    series: 3000,
    cores: 8,
    graphics: false,
    socket: 'AM4',
    tdp: 65,
    pcie: 4,
    price: 5,
    solutions: ['RTX 3050', 'RTX 3060', 'RTX 4060'],
  },
  {
    category: ['default', 'gaming', 'hardwork'],
    firm: 'AMD',
    branding: 'Ryzen 7',
    model: '3800X',
    series: 3000,
    cores: 8,
    graphics: false,
    socket: 'AM4',
    tdp: 105,
    pcie: 4,
    price: 6,
    solutions: ['RTX 3050', 'RTX 3060', 'RTX 4060'],
  },
  {
    category: ['default', 'gaming', 'hardwork', 'extreme'],
    firm: 'AMD',
    branding: 'Ryzen 9',
    model: '3900X',
    series: 3000,
    cores: 12,
    graphics: false,
    socket: 'AM4',
    tdp: 105,
    pcie: 4,
    price: 7,
    solutions: [
      'RTX 3070',
      'RTX 3070 Ti',
      'RTX 4060',
      'RTX 4060 Ti',
      'RTX 4070',
      'RTX 4070 Ti',
    ],
  },
  {
    category: ['default', 'gaming', 'hardwork', 'extreme'],
    firm: 'AMD',
    branding: 'Ryzen 9',
    model: '3950X',
    series: 3000,
    cores: 16,
    graphics: false,
    socket: 'AM4',
    tdp: 105,
    pcie: 4,
    price: 8,
    solutions: [
      'RTX 3070 Ti',
      'RTX 4060',
      'RTX 4060 Ti',
      'RTX 4070',
      'RTX 4070 Ti',
      'RTX 4080',
    ],
  },
  {
    category: ['default', 'gaming'],
    firm: 'AMD',
    branding: 'Ryzen 5',
    model: '5500',
    series: 5000,
    cores: 6,
    graphics: false,
    socket: 'AM4',
    tdp: 65,
    pcie: 3,
    price: 1,
    solutions: [
      'GTX 1660 super',
      'GTX 1660 Ti',
      'RTX 3050',
      'RTX 3060',
      'RTX 3060 Ti',
      'RTX 4060',
    ],
  },
  {
    category: ['default', 'gaming'],
    firm: 'AMD',
    branding: 'Ryzen 5',
    model: '5600G',
    series: 5000,
    cores: 6,
    graphics: true,
    socket: 'AM4',
    tdp: 65,
    pcie: 3,
    price: 2,
    solutions: ['Vega'],
  },
  {
    category: ['default', 'gaming'],
    firm: 'AMD',
    branding: 'Ryzen 5',
    model: '5600',
    series: 5000,
    cores: 6,
    graphics: false,
    socket: 'AM4',
    tdp: 65,
    pcie: 4,
    price: 3,
    solutions: ['RTX 3050', 'RTX 3060', 'RTX 3060 Ti', 'RTX 4060'],
  },
  {
    category: ['default', 'gaming'],
    firm: 'AMD',
    branding: 'Ryzen 5',
    model: '5600X',
    series: 5000,
    cores: 6,
    graphics: false,
    socket: 'AM4',
    tdp: 65,
    pcie: 4,
    price: 4,
    solutions: [
      'RTX 3050',
      'RTX 3060',
      'RTX 3060 Ti',
      'RTX 3070',
      'RTX 3070 Ti',
      'RTX 4060',
      'RTX 4060 Ti',
      'RTX 4070',
    ],
  },
  {
    category: ['default', 'gaming', 'hardwork'],
    firm: 'AMD',
    branding: 'Ryzen 7',
    model: '5700G',
    series: 5000,
    cores: 8,
    graphics: true,
    socket: 'AM4',
    tdp: 65,
    pcie: 3,
    price: 5,
    solutions: ['Vega'],
  },
  {
    category: ['default', 'gaming', 'hardwork'],
    firm: 'AMD',
    branding: 'Ryzen 7',
    model: '5700X',
    series: 5000,
    cores: 8,
    graphics: false,
    socket: 'AM4',
    tdp: 65,
    pcie: 4,
    price: 6,
    solutions: [
      'RTX 3060',
      'RTX 3060 Ti',
      'RTX 3070',
      'RTX 3070 Ti',
      'RTX 4060',
      'RTX 4060 Ti',
      'RTX 4070',
      'RTX 4070 Ti',
    ],
  },
  {
    category: ['default', 'gaming', 'hardwork'],
    firm: 'AMD',
    branding: 'Ryzen 7',
    model: '5800X',
    series: 5000,
    cores: 8,
    graphics: false,
    socket: 'AM4',
    tdp: 105,
    pcie: 4,
    price: 7,
    solutions: [
      'RTX 3060',
      'RTX 3060 Ti',
      'RTX 3070',
      'RTX 3080',
      'RTX 3080 Ti',
      'RTX 3090',
      'RTX 4060',
      'RTX 4060 Ti',
      'RTX 4070',
      'RTX 4070 Ti',
      'RTX 4080',
    ],
  },
  {
    category: ['default', 'gaming', 'hardwork', 'extreme'],
    firm: 'AMD',
    branding: 'Ryzen 9',
    model: '5900X',
    series: 5000,
    cores: 12,
    graphics: false,
    socket: 'AM4',
    tdp: 105,
    pcie: 4,
    price: 8,
    solutions: [
      'RTX 3070 Ti',
      'RTX 3080',
      'RTX 3080 Ti',
      'RTX 3090',
      'RTX 4060',
      'RTX 4060 Ti',
      'RTX 4070',
      'RTX 4070 Ti',
      'RTX 4080',
      'RTX 4090',
    ],
  },
  {
    category: ['default', 'gaming', 'hardwork', 'extreme'],
    firm: 'AMD',
    branding: 'Ryzen 9',
    model: '5950X',
    series: 5000,
    cores: 16,
    graphics: false,
    socket: 'AM4',
    tdp: 105,
    pcie: 4,
    price: 9,
    solutions: [
      'RTX 3070 Ti',
      'RTX 3080',
      'RTX 4060',
      'RTX 4060 Ti',
      'RTX 4070',
    ],
  },
  {
    category: ['default', 'gaming'],
    firm: 'AMD',
    branding: 'Ryzen 5',
    model: '7600',
    series: 7000,
    cores: 6,
    graphics: false,
    socket: 'AM5',
    tdp: 65,
    pcie: 4,
    price: 1,
    solutions: [
      'RTX 3060 Ti',
      'RTX 3070',
      'RTX 3070 Ti',
      'RTX 3080',
      'RTX 3080 Ti',
      'RTX 4060',
      'RTX 4060 Ti',
      'RTX 4070',
      'RTX 4070 Ti',
    ],
  },
  {
    category: ['default', 'gaming'],
    firm: 'AMD',
    branding: 'Ryzen 5',
    model: '7600X',
    series: 7000,
    cores: 6,
    graphics: false,
    socket: 'AM5',
    tdp: 105,
    pcie: 4,
    price: 2,
    solutions: [
      'RTX 3070',
      'RTX 3070 Ti',
      'RTX 3080',
      'RTX 3080 Ti',
      'RTX 3090',
      'RTX 4060',
      'RTX 4060 Ti',
      'RTX 4070',
      'RTX 4070 Ti',
      'RTX 4080',
    ],
  },
  {
    category: ['default', 'gaming', 'hardwork'],
    firm: 'AMD',
    branding: 'Ryzen 7',
    model: '7700',
    series: 7000,
    cores: 8,
    graphics: false,
    socket: 'AM5',
    tdp: 65,
    pcie: 4,
    price: 3,
    solutions: [
      'RTX 3080',
      'RTX 3080 Ti',
      'RTX 3090',
      'RTX 4060 Ti',
      'RTX 4070',
      'RTX 4070 Ti',
      'RTX 4080',
    ],
  },
  {
    category: ['default', 'gaming', 'hardwork'],
    firm: 'AMD',
    branding: 'Ryzen 7',
    model: '7700X',
    series: 7000,
    cores: 8,
    graphics: false,
    socket: 'AM5',
    tdp: 105,
    pcie: 4,
    price: 4,
    solutions: [
      'RTX 3070 Ti',
      'RTX 3080',
      'RTX 3080 Ti',
      'RTX 3090',
      'RTX 4070',
      'RTX 4070 Ti',
      'RTX 4080',
    ],
  },
  {
    category: ['default', 'gaming', 'hardwork', 'extreme'],
    firm: 'AMD',
    branding: 'Ryzen 9',
    model: '7900',
    series: 7000,
    cores: 12,
    graphics: false,
    socket: 'AM5',
    tdp: 65,
    pcie: 4,
    price: 5,
    solutions: [
      'RTX 3070 Ti',
      'RTX 3080',
      'RTX 3080 Ti',
      'RTX 3090',
      'RTX 4070',
      'RTX 4070 Ti',
      'RTX 4080',
      'RTX 4090',
    ],
  },
  {
    category: ['default', 'gaming', 'hardwork', 'extreme'],
    firm: 'AMD',
    branding: 'Ryzen 9',
    model: '7900X',
    series: 7000,
    cores: 12,
    graphics: false,
    socket: 'AM5',
    tdp: 170,
    pcie: 4,
    price: 6,
    solutions: [
      'RTX 3070',
      'RTX 3070 Ti',
      'RTX 3080',
      'RTX 3080 Ti',
      'RTX 3090',
      'RTX 4070 Ti',
      'RTX 4080',
      'RTX 4090',
    ],
  },
  {
    category: ['default', 'gaming', 'hardwork', 'extreme'],
    firm: 'AMD',
    branding: 'Ryzen 9',
    model: '7950X',
    series: 7000,
    cores: 16,
    graphics: false,
    socket: 'AM5',
    tdp: 170,
    pcie: 4,
    price: 7,
    solutions: [
      'RTX 3070 Ti',
      'RTX 3080',
      'RTX 3080 Ti',
      'RTX 3090',
      'RTX 4070 Ti',
      'RTX 4080',
      'RTX 4090',
    ],
  },
];

export const gpu = [
  {
    firm: 'AMD',
    model: 'Vega',
    perfomance: 0,
    dlss: 0,
    rtx: 0,
    gaming: true,
    tdp: 0,
    price: 0,
    pcie: 3,
  },
  {
    firm: 'NVIDIA',
    model: 'GTX 1650',
    perfomance: 1,
    dlss: 0,
    rtx: 0,
    gaming: true,
    tdp: 75,
    price: 1,
    pcie: 3,
  },
  {
    firm: 'NVIDIA',
    model: 'GTX 1650 Super',
    perfomance: 2,
    dlss: 0,
    rtx: 0,
    gaming: true,
    tdp: 100,
    price: 2,
    pcie: 3,
  },
  {
    firm: 'NVIDIA',
    model: 'GTX 1660',
    dlss: 0,
    rtx: 0,
    perfomance: 3,
    gaming: true,
    tdp: 120,
    price: 3,
    pcie: 3,
  },
  {
    firm: 'NVIDIA',
    model: 'GTX 1660 super',
    dlss: 0,
    rtx: 0,
    perfomance: 4,
    gaming: true,
    tdp: 125,
    price: 4,
    pcie: 3,
  },
  {
    firm: 'NVIDIA',
    model: 'GTX 1660 Ti',
    dlss: 0,
    rtx: 0,
    perfomance: 5,
    gaming: true,
    tdp: 120,
    price: 5,
    pcie: 3,
  },
  {
    firm: 'NVIDIA',
    model: 'RTX 3050',
    dlss: 2,
    rtx: 2,
    perfomance: 6,
    gaming: true,
    tdp: 130,
    price: 6,
    pcie: 3,
  },
  {
    firm: 'NVIDIA',
    model: 'RTX 3060',
    dlss: 2,
    rtx: 2,
    perfomance: 7,
    gaming: true,
    tdp: 170,
    price: 7,
    pcie: 3,
  },
  {
    firm: 'NVIDIA',
    model: 'RTX 3060 Ti',
    dlss: 2,
    rtx: 2,
    perfomance: 8,
    gaming: true,
    tdp: 200,
    price: 8,
    pcie: 3,
  },
  {
    firm: 'NVIDIA',
    model: 'RTX 3070',
    perfomance: 9,
    dlss: 2,
    rtx: 2,
    gaming: true,
    tdp: 220,
    price: 9,
    pcie: 4,
  },
  {
    firm: 'NVIDIA',
    model: 'RTX 3070 Ti',
    perfomance: 10,
    dlss: 2,
    rtx: 2,
    gaming: true,
    tdp: 290,
    price: 10,
    pcie: 4,
  },
  {
    firm: 'NVIDIA',
    model: 'RTX 3080',
    perfomance: 11,
    dlss: 2,
    rtx: 2,
    gaming: true,
    tdp: 320,
    price: 11,
    pcie: 4,
  },
  {
    firm: 'NVIDIA',
    model: 'RTX 3080 Ti',
    perfomance: 12,
    dlss: 2,
    rtx: 2,
    gaming: true,
    tdp: 350,
    price: 12,
    pcie: 4,
  },
  {
    firm: 'NVIDIA',
    model: 'RTX 3090',
    perfomance: 13,
    dlss: 2,
    rtx: 2,
    gaming: true,
    tdp: 350,
    price: 13,
    pcie: 4,
  },
  {
    firm: 'NVIDIA',
    model: 'RTX 3090 Ti',
    perfomance: 14,
    dlss: 2,
    rtx: 2,
    gaming: true,
    tdp: 450,
    price: 14,
    pcie: 4,
  },
  {
    firm: 'NVIDIA',
    model: 'RTX 4060',
    perfomance: 7,
    dlss: 3,
    rtx: 3,
    gaming: true,
    tdp: 115,
    price: 9,
    pcie: 4,
  },
  {
    firm: 'NVIDIA',
    model: 'RTX 4060 Ti',
    perfomance: 8,
    dlss: 3,
    rtx: 3,
    gaming: true,
    tdp: 165,
    price: 10,
    pcie: 4,
  },
  {
    firm: 'NVIDIA',
    model: 'RTX 4070',
    perfomance: 9,
    dlss: 3,
    rtx: 3,
    gaming: true,
    tdp: 200,
    price: 11,
    pcie: 4,
  },
  {
    firm: 'NVIDIA',
    model: 'RTX 4070 Ti',
    perfomance: 10,
    dlss: 3,
    rtx: 3,
    gaming: true,
    tdp: 285,
    price: 12,
    pcie: 4,
  },
  {
    firm: 'NVIDIA',
    model: 'RTX 4080',
    perfomance: 11,
    dlss: 3,
    rtx: 3,
    gaming: true,
    tdp: 320,
    price: 14,
    pcie: 4,
  },
  {
    firm: 'NVIDIA',
    model: 'RTX 4090',
    perfomance: 12,
    dlss: 3,
    rtx: 3,
    gaming: true,
    tdp: 450,
    price: 16,
    pcie: 4,
  },
];

export const motherboards = [
  {
    chipset: 'A320',
    socket: 'AM4',
    solutions: {
      branding: ['Ryzen 3'],
      series: [1000, 2000, 3000],
    },
    ram: ['DDR4'],
    pcie: [3],
    overclocking: false,
    price: 1,
  },
  {
    chipset: 'B350',
    socket: 'AM4',
    solutions: {
      branding: ['Ryzen 3', 'Ryzen 5'],
      series: [1000, 2000, 3000, 5000],
    },
    ram: ['DDR4'],
    pcie: [3],
    overclocking: true,
    price: 2,
  },
  {
    chipset: 'X370',
    socket: 'AM4',
    solutions: {
      branding: ['Ryzen 3', 'Ryzen 5', 'Ryzen 7', 'Ryzen 9'],
      series: [1000, 2000, 3000, 5000],
    },
    ram: ['DDR4'],
    pcie: [4],
    overclocking: true,
    price: 3,
  },
  {
    chipset: 'B450',
    socket: 'AM4',
    solutions: {
      branding: ['Ryzen 3', 'Ryzen 5', 'Ryzen 7'],
      series: [1000, 2000, 3000, 5000],
    },
    ram: ['DDR4'],
    pcie: [3],
    overclocking: true,
    price: 3,
  },
  {
    chipset: 'X470',
    socket: 'AM4',
    solutions: {
      branding: ['Ryzen 3', 'Ryzen 5', 'Ryzen 7', 'Ryzen 9'],
      series: [1000, 2000, 3000, 5000],
    },
    ram: ['DDR4'],
    pcie: [4],
    overclocking: true,
    price: 4,
  },
  {
    chipset: 'A520',
    socket: 'AM4',
    solutions: {
      branding: ['Ryzen 5'],
      series: [1000, 2000, 3000, 5000],
    },
    ram: ['DDR4'],
    pcie: [4],
    overclocking: false,
    price: 3,
  },
  {
    chipset: 'B550',
    socket: 'AM4',
    solutions: {
      branding: ['Ryzen 3', 'Ryzen 5', 'Ryzen 7'],
      series: [1000, 2000, 3000, 5000],
    },
    ram: ['DDR4'],
    pcie: [4],
    overclocking: true,
    price: 4,
  },
  {
    chipset: 'X570',
    socket: 'AM4',
    solutions: {
      branding: ['Ryzen 3', 'Ryzen 5', 'Ryzen 7', 'Ryzen 9'],
      series: [1000, 2000, 3000, 5000],
    },
    ram: ['DDR4'],
    pcie: [4],
    overclocking: true,
    price: 5,
  },
  {
    chipset: 'A620',
    socket: 'AM5',
    solutions: {
      branding: ['Ryzen 3', 'Ryzen 5'],
      series: [7000],
    },
    ram: ['DDR5'],
    pcie: [4],
    overclocking: false,
    price: 4,
  },
  {
    chipset: 'A650',
    socket: 'AM5',
    solutions: {
      branding: ['Ryzen 3', 'Ryzen 5', 'Ryzen 7'],
      series: [7000],
    },
    ram: ['DDR5'],
    pcie: [4],
    overclocking: true,
    price: 5,
  },
  {
    chipset: 'X670',
    socket: 'AM5',
    solutions: {
      branding: ['Ryzen 3', 'Ryzen 5', 'Ryzen 7', 'Ryzen 9'],
      series: [7000],
    },
    ram: ['DDR5'],
    pcie: [4],
    overclocking: true,
    price: 6,
  },
];

const configurations = [];

for (let i = 0; i < cpu.length; i++) {
  for (let j = 0; j < gpu.length; j++) {
    const currentCpu = cpu[i];
    const currentGpu = gpu[j];

    if (
      currentGpu.pcie > currentCpu.pcie ||
      !currentCpu.solutions.includes(currentGpu.model)
    ) {
      continue;
    }

    let chipset, chipsetIndex;

    for (const motherboard of motherboards) {
      if (
        motherboard.socket === currentCpu.socket &&
        motherboard.solutions.branding.includes(currentCpu.branding) &&
        motherboard.solutions.series.includes(currentCpu.series) &&
        motherboard.pcie.includes(currentGpu.pcie)
      ) {
        chipset = motherboard.chipset;
        chipsetIndex = motherboard.price;

        break;
      }
    }

    const configurationTdp = currentCpu.tdp + currentGpu.tdp;

    const powerUnit = Math.ceil((configurationTdp * 2.25) / 100) * 100;

    const cpuIndex =
      currentCpu.cores * (currentCpu.series / 1000) * currentCpu.price;

    const gpuIndex =
      currentGpu.perfomance *
      (currentGpu.dlss + currentGpu.rtx) *
      currentGpu.price;

    const configurationTdpIndex = configurationTdp / 1000;

    let currentIndex =
      cpuIndex + gpuIndex + configurationTdpIndex + chipsetIndex;

    configurations.push({
      cpu: `${currentCpu.firm} ${currentCpu.branding} ${currentCpu.model}`,
      gpu: `${currentGpu.firm} ${currentGpu.model}`,
      chipset: chipset,
      powerUnit: powerUnit,
      index: currentIndex,
    });
  }
}

configurations.sort((a, b) => a.index - b.index);

console.log(configurations.length);

for (const configuration of configurations) {
  console.log(configuration);
}
